dataset_name: "mimic-cxr"
model_name: "ViT-B/16" # ViT-L/14, ViT-B/16, ViT-B/32
mode: "adapters" # ["adapters", "freeze", "train_norm", "full", "train_mlp_norm"]

lr: 5e-5
weight_decay: 0.2 # decay 0.05 in convnext, 0.2 in CLIP training
use_augs: True
sent_frac: 0.8 # proportion of sentences to sample during CL
precision: 16
max_epochs: 10
val_check_interval: 1500
gen_freq: 15
batch_size:
dataset_size:

gpu: 2

text2img_num_steps: 100
text2img_num_feats: 0

mixup_alpha: 0.0
mixup_labels: False
add_noise_level: 0.0
mult_noise_level: 0.0

use_ffcv: False
debug: 0
seed: 0
num_workers: 16
pin_memory: True
hydra.output_subdir:
